### ISSUE TITLE
AD: 네이버카페 app

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#687] opened 2023-04-22 04:41 UTC
### URL

https://apps.apple.com/kr/app/%EB%84%A4%EC%9D%B4%EB%B2%84-%EC%B9%B4%ED%8E%98-naver-cafe/id420615104

https://cafe.naver.com/appleiphone/7890043

### FILTERS

adguard base
adguard mobile
listkr

adguard dns
listkr dns

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 네이버카페 앱 에서 광고차단 부탁드립니다

![IMG_2482](https://user-images.githubusercontent.com/15683789/233762898-8ab549f0-3ce5-497d-9808-f4594acade56.png)
![IMG_2483](https://user-images.githubusercontent.com/15683789/233762906-cf8f2fa6-639a-45bf-ad35-a43c0fb14dd4.jpeg)

**Comment by piquark6046** [comment] 2023-04-24 10:31
Duplicate of #686

**Closed as not planned by piquark6046** 2023-04-24 10:31 UTC
Labels: advertisement user
